services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - entrevista_red
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ${NAME}
      DB_USER: ${USER}
      DB_PASSWORD: ${PASSWORD}
    networks:
      - entrevista_red
volumes:
  db_data:
networks:
  entrevista_red:
    driver: bridge